@echo off
mode con: cols=71 lines=50
cls
:: Set download folder
set "dlFolder=%USERPROFILE%\Downloads\Spotify-Downloads"

:: Create folder if it doesn't exist
if not exist "%dlFolder%" (
    mkdir "%dlFolder%"
)

:: Check if SpotDL is available
where spotdl >nul 2>nul
if errorlevel 1 (
    echo ❌ SpotDL is not installed!
    echo Installing SpotDL using pip...
    echo.

    pip install spotdl

    echo.
    echo SpotDL installation attempted. Please reopen the tool if installation was successful.
    pause
    exit /b
)
echo.            
echo [96m[=====================================================================]
echo.                   
echo                                      [92m..         
echo                                   ......        
echo                                 .........       
echo                                ..........       
echo                               ......  ...       
echo                               ....   ....       
echo                               ...  ......       
echo                               ..........        
echo                            ............         
echo                         .............           
echo                      .............              
echo                    ........... .....            
echo                   ........  .............       
echo                  .......  .................     
echo                 ......   ...................    
echo                 .....   .....   ...   .......   
echo                 .....    ...    ...     .....   
echo                  .....   ....   ...     .....   
echo                   ......   .... ...    .....    
echo                     ........     .........      
echo                        .................        
echo                             ........            
echo                       .          ...            
echo                   .........      ....           
echo                  ..........      ...            
echo                  ..........     ....            
echo                   ........   ......             
echo                    ..............               
echo                       ........[0m 
echo.
echo [96m[=====================================================================]
echo                 [93mSpotify Downloader                 [1mBY - Hajisab
echo [96m[=====================================================================][92m
echo.
                      

:: Prompt for Spotify link
set /p link=Enter Spotify track/playlist link: 

:: Run SpotDL and download
echo.
echo Downloading to: %dlFolder%
echo.
spotdl "%link%" --output "%dlFolder%\%(title)s.%(ext)s"

echo.
echo  Download complete!
echo.
echo Download at: %dlFolder%
pause
cd..
start StartDownloader.bat
exit